#from .Splash import Splash
#from .woodcutter import OSRSWoodcutter
#from .fishing import OSRSFishing
#from .fishcook import OSRSFishCook
from .cwoodcutting import OSRSWoodcutting
#from .csmelter import OSRSSmelter
#from .csmither import OSRSSmither
#from .cnecksmelt import OSRSNecksmelt
from .cmining import OSRSMining
from .MiningGuild.cminingguild import OSRSMiningGuild
#from .PotionMaker.Potion_Maker import OSRSPotionMaker
from .cminingtpower import OSRSMiningTpower
#from .combat.combat import OSRSCombat
from .cAddyRock import OSRSAddyRock
from .HighAlch import OSRSHighAlch
from .cjugs import OSRSJugs
from .cFiremaking import OSRSFiremaking

from .WillowsDad.WDCombat import OSRSWDCombat
from .WillowsDad.WDWoodcutting import OSRSWDWoodcutting
from .WillowsDad.WDUltraCompost import OSRSWDUltraCompostMaker
from .WillowsDad.WDDegrimer import OSRSWDDegrimer
from .WillowsDad.WDFishing import OSRSWDFishing
from .WillowsDad.WillowsDad_bot import WillowsDadBot
from .WillowsDad.WDMining import OSRSWDMining
from .WillowsDad.WDFiremaking import OSRSWDFiremaking